include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false

analyzer:
  language:
    strict-casts: true
