[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "aarch64-linux-android-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "x86_64-linux-android-ar"
